### PR TITLE
Added support for Tauri v2

### PR DESCRIPTION
**Pull request by reyamir**
**Changes**:

- Support Tauri v2
- Upgrade `gtk` to `0.18`

I'm not sure my solution is best, but it's working in my app

### CODE REVIEW

**Comment by wyhaya** [comment]
Here are some questions:

1. `saved_theme_value` should accept a `file path`, you are currently passing a `directory`.
2. You only changed macOS and forgot about Linux and Windows.

Since tauri v2 changed the api, I recommend modifying these fn

```diff
- pub(crate) fn saved_theme_value(path: &PathBuf) -> Theme
+ pub(crate) fn saved_theme_value<R: Runtime>(app: AppHandle<R>) -> Theme 

- pub(crate) fn save_theme_value(path: &PathBuf, theme: Theme)
+ pub(crate) fn save_theme_value<R: Runtime>(app: AppHandle<R>, theme: Theme)
```
It will be simpler. Just some suggestions

**Comment by wyhaya** [comment]
Thanks, but there are still some problems, I will fix it in another commit

**Comment by reyamir** [comment]
oh thank you, I'm still struggling at it 😅

**Comment by wyhaya** [comment]
New version (0.3.0) released to crates.io

**Pull request merged**
